version: "3.9"

services:
  db:
    image: postgresbackups:latest
    volumes:
      - ./conf/postgresql.conf:/etc/postgresql.conf
      - ./db-data:/var/lib/postgresql/data
      - ./logs:/var/log/backups/
    env_file:
      - ./.env